### ISSUE TITLE
Corpus sharing

### ISSUE THREAD

**Issue by Dsakula** [Aadil101/BigGreen-at-LCP-2021#2]
Hello, I found that “google_ngram. npy”, SUBTLEXus related “SUBTLEXus74286wordtextversion. tsv”, and Bnc related “word_frequency/all. num” were used in the experiment during the reproduction process, but these processed corpora were not found in the files you provided. If you can supplement the upload, I will be very grateful

**Comment by Aadil101** [comment]
Absolutely, I can help you reproduce the files.

You can obtain "SUBTLEXus74286wordtextversion.tsv" by locating the **Download the new frequency measures** section at the link below and downloading the file **Zipped Text version with all 74,286 words in the corpus**. After unzipping it, you will obtain a text file, but you can export this to .tsv or .csv format using Excel or the like:

https://www.ugent.be/pp/experimentele-psychologie/en/research/documents/subtlexus

You can obtain "all.num" by locating the **Unlemmatised lists** section at the link below and downloading either "all.num.gz", "all.num.o5", or "all.num.o5.gz" (whichever is more convenient to uncompress on your machine):

http://www.kilgarriff.co.uk/bnc-readme.html

Regarding what I think you're referring to as the ```{single/multi}_{train/trial/test}_google_ngram_{n-gram length}.npy``` files, I imagine your goal is to take a set of tokens (these can be single or multi-word) and create a numpy array containing Google Books Ngrams frequencies. 

You can compute each frequency by passing the token into the ```get_tf``` function located in [macbook/lib/utils.py](https://github.com/Aadil101/BigGreen-at-LCP-2021/blob/master/macbook/lib/utils.py). Now if you have a set of tokens stored in a Pandas Series and would like to automate the computation, you can check out the **Mo' features** section of [macbook/pipeline.ipynb](https://github.com/Aadil101/BigGreen-at-LCP-2021/blob/master/macbook/pipeline.ipynb) and find the following blocks of code:

```python
tokens = set(single_trial['token'])
token_2_mc = {}
for token in tqdm(tokens):
    token_2_mc[token] = get_tf(token)
    time.sleep(0.001)
```

```python
google_ngram = single_trial['token'].apply(lambda x: token_2_mc[x]).to_numpy()
```

Hope this helps :)
